Preventing NoClassDefFoundError when IC2 is missing
- Prevent referring to `new EnergyTileLoadEvent(...)` and `new EnergyTileUnloadEvent(...)`
- Fixes #14